package tablut.gui;

import tablut.listeners.ChangePlayersSettingsListener;
import tablut.events.ChangePlayersSettingsEvent;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JComboBox;
import tablut.ComputerPlayer;
import tablut.Manager;
import tablut.Player;

/**
 * Nastavení hráčů.
 *
 * @author Ondřej Tom
 */
public class GUIPlayersSettings extends javax.swing.JFrame
{
	/**
	 * Manažer hry.
	 */
	private Manager manager;


	/**
	 * Posluchači události změny nastavení hráčů.
	 */
	List<ChangePlayersSettingsListener> listeners = new ArrayList<>();


	/**
	 * @param manager
	 */
	public GUIPlayersSettings(Manager manager)
	{
		// Zamezíme roztahování okna.
		this.setResizable(false);

		// Nastavíme manažera hry.
		this.manager = manager;

		// Inicializace komponent.
		initComponents();

		// Nastavení zavření okna.
		this.setDefaultCloseOperation(HIDE_ON_CLOSE);

		// Nastavení tlačítek pro změnu hráčů.
		setChangePlayerTypeListener(russianPlayer, difficultyRussians);
		setChangePlayerTypeListener(swedePlayer, difficultySwedes);

		// Nastavení hodnot.
		initValues();

		// Nastavení rozměrů.
		Dimension screenDim = Toolkit.getDefaultToolkit().getScreenSize();
		setLocation(((screenDim.width - getSize().width) / 2), (screenDim.height - getSize().height) / 2);
	}


	/**
	 * Přidá posluchače.
	 *
	 * @param listener
	 */
	public void addListener(ChangePlayersSettingsListener listener)
	{
		listeners.add(listener);
	}


	/**
	 * Nastaví manažera hry.
	 *
	 * @param manager
	 */
	public void setManager(Manager manager)
	{
		this.manager = manager;
		initValues();
	}


	/**
	 * Inicializace volby hráče.
	 *
	 * @param player
	 * @param playerSelection
	 * @param difficultySelection
	 */
	private void initPlayerValue(Player player, JComboBox playerSelection, JComboBox difficultySelection)
	{
		// Nastavení počítače.
		if (player instanceof ComputerPlayer)
		{
			ComputerPlayer computerPlayer = (ComputerPlayer) player;
			int difficulty = computerPlayer.getDifficulty();

			playerSelection.setSelectedIndex(1);
			difficultySelection.setEnabled(true);
			difficultySelection.setSelectedIndex(difficulty - 2);
		}
		// Nastavení lidského hráče.
		else
		{
			playerSelection.setSelectedIndex(0);
			difficultySelection.setEnabled(false);
		}
	}


	/**
	 * Nastaví hodnoty talčítek pro volbu hráčů.
	 */
	private void initValues()
	{
		Player playerA = manager.getPlayerA();
		Player playerB = manager.getPlayerB();

		initPlayerValue(playerA, russianPlayer, difficultyRussians);
		initPlayerValue(playerB, swedePlayer, difficultySwedes);
	}


	// Nastavení posluchače pro změnu nastavení.
	private void setChangePlayerTypeListener(JComboBox playerType, final JComboBox difficulty)
	{
		playerType.addItemListener(new ItemListener() {

			@Override
			public void itemStateChanged(ItemEvent e)
			{
				if (e.getStateChange() == ItemEvent.SELECTED)
				{
					if (e.getItem().toString().equals("computer"))
					{
						difficulty.setEnabled(true);
					}
					else
					{
						difficulty.setEnabled(false);
					}
				}
			}

		});
	}


	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        russiansLabel = new javax.swing.JLabel();
        russianPlayer = new javax.swing.JComboBox();
        difficultyRussiansLabel = new javax.swing.JLabel();
        difficultyRussians = new javax.swing.JComboBox();
        swedesLabel = new javax.swing.JLabel();
        swedePlayer = new javax.swing.JComboBox();
        difficultySwedesLabel = new javax.swing.JLabel();
        difficultySwedes = new javax.swing.JComboBox();
        jPanel1 = new javax.swing.JPanel();
        cancelButton = new javax.swing.JButton();
        okButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        russiansLabel.setText("Russians");

        russianPlayer.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "human", "computer" }));
        russianPlayer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                russianPlayerActionPerformed(evt);
            }
        });

        difficultyRussiansLabel.setText("Difficulty");

        difficultyRussians.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "easy", "medium", "hard" }));
        difficultyRussians.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                difficultyRussiansActionPerformed(evt);
            }
        });

        swedesLabel.setText("Swedes");

        swedePlayer.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "human", "computer" }));

        difficultySwedesLabel.setText("Difficulty");

        difficultySwedes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "easy", "medium", "hard" }));

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 11, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton)
                    .addComponent(okButton)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(russiansLabel)
                    .addComponent(swedesLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(russianPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(swedePlayer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(difficultyRussiansLabel)
                        .addGap(18, 18, 18)
                        .addComponent(difficultyRussians, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(difficultySwedesLabel)
                        .addGap(18, 18, 18)
                        .addComponent(difficultySwedes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(russiansLabel)
                    .addComponent(russianPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(difficultyRussiansLabel)
                    .addComponent(difficultyRussians, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(swedesLabel)
                    .addComponent(swedePlayer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(difficultySwedesLabel)
                    .addComponent(difficultySwedes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void russianPlayerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_russianPlayerActionPerformed

    }//GEN-LAST:event_russianPlayerActionPerformed

    private void difficultyRussiansActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_difficultyRussiansActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_difficultyRussiansActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
		this.setVisible(false);
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
		for (ChangePlayersSettingsListener listener : listeners)
		{
			listener.changePlayersSettings(new ChangePlayersSettingsEvent(this, russianPlayer.getSelectedIndex(), difficultyRussians.getSelectedIndex(), swedePlayer.getSelectedIndex(), difficultySwedes.getSelectedIndex()));
		}

		this.setVisible(false);
    }//GEN-LAST:event_okButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JComboBox difficultyRussians;
    private javax.swing.JLabel difficultyRussiansLabel;
    private javax.swing.JComboBox difficultySwedes;
    private javax.swing.JLabel difficultySwedesLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton okButton;
    private javax.swing.JComboBox russianPlayer;
    private javax.swing.JLabel russiansLabel;
    private javax.swing.JComboBox swedePlayer;
    private javax.swing.JLabel swedesLabel;
    // End of variables declaration//GEN-END:variables
}
